name := "akka-http-demo"
version := "0.1"
scalaVersion := "2.13.3"
organization := "com.knoldus"

libraryDependencies +="com.typesafe.akka" %% "akka-actor" % "2.5.26"
libraryDependencies +="com.typesafe.akka" %% "akka-http"   % "10.1.12"
libraryDependencies +="com.typesafe.akka" %% "akka-stream" % "2.5.26"
libraryDependencies += "com.typesafe.akka" %% "akka-http-spray-json" % "10.1.12"
libraryDependencies += "de.heikoseeberger" %% "akka-http-circe" % "1.29.1"
libraryDependencies += "io.circe" %% "circe-generic" % "0.12.3"
libraryDependencies +="ch.qos.logback" % "logback-classic" % "1.2.3"
libraryDependencies += "org.mongodb.scala" %% "mongo-scala-driver" % "4.0.5"
libraryDependencies += "ch.rasc" % "bsoncodec" % "1.0.1"
